### PR TITLE
refactor to add multiple driver, adding memory store

### LINKED ISSUE #35: in-memory rate limiting
Is in-memory only rate limiting supported? If so, it would be great to update the readme. if not, we'd love to see it added. (Running a toy webiste on a single server and don't want the overhead of setting up redis right now).

Express-rate-limit has this[1], and it would be great if some koa middleware has this as well.

https://github.com/nfriedly/express-rate-limit/blob/master/lib/memory-store.js

### PR DESCRIPTION
**Pull request by tuananh**
Attempt to fix #35

### CODE REVIEW

**Comment by towertop** [comment]
@tuananh 

Hi, you might need to update the `files` field in  `package.json` as well to include new files:

    "files": [
      "index.js",
      "limiter/memory.js",
      "limiter/redis.js",
    ]

Otherwise i guess it would cause problem when releasing to npm repo.

**Comment by haoxins** [comment]
LGTM if we can update `files` field in package.json just as @towertop said :)

**Comment by haoxins** [comment]
I will try to merge this and release a new version within this/next week :)

**Comment by JS1010111** [comment]
Hi @haoxins , do you have any idea when you'll have time to merge this? Thanks!

**Comment by haoxins** [comment]
it seems that no any broken change, will publish a new `MINOR` version

**Comment by haoxins** [comment]
`v4.3.0`

**Pull request merged**
