### PR TITLE
Added support for custom error message

### PR DESCRIPTION
**Pull request by Volox**
Removed unused dependency `ms`.

### CODE REVIEW

**Comment by fixe** [comment]
@Volox can you please add a test and remove the body from the first commit? Also, it would be cool to ignore the body completely.

**Comment by Volox** [comment]
@fixe just added a test.

Just a question, how i can remove the body from a commit without messing up the history (eg. rebase)?

**Comment by fixe** [comment]
@Volox you can do a `git rebase origin/master` and go from there.
Also, `git commit --amend` is your friend :-)

**Comment by Volox** [comment]
@fixe Done!

**Comment by fixe** [comment]
@Volox can you add the option to remove the body completely? Or do you want me to do it?

**Comment by Volox** [comment]
@fixe mmm ok... in this case only the status is set right?

**Comment by fixe** [comment]
Correct.

**Comment by coderhaoxin** [comment]
v2.4.0

**Pull request closed without merging**
