### PR TITLE
Update to koa 2

### PR DESCRIPTION
**Pull request by andyhu**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
1. rebase please :)
2. CI failed

**Comment by andyhu** [comment]
Hmm, couldn't figure out why there is a failed test. Why it shows 404 error rather than correctly throw the error. Could anyone take a look? Many thanks!

**Comment by andyhu** [comment]
It should pass the tests nnow

**Comment by dead-horse** [comment]
it better to create a `next` branch to support koa@2.

and personally -1 to rewrite with raw promise(without async await). can't we just use `koa-convert` to support koa@2 now?

**Comment by andyhu** [comment]
Well, what do you mean raw promise? There's no additional Promise libraries used nor native Promise. Just thenify which already exists since v1.

**Comment by dead-horse** [comment]
actually I'm dislike direct using promise in koa's middleware, It was design for async await. I'd rather using generator function for now(without async await being native).

**Comment by coderhaoxin** [comment]
> what do you mean raw promise?

Use async & await !

> can't we just use koa-convert to support koa@2 now?

+1

**Comment by coderhaoxin** [comment]
closed by #26

**Pull request closed without merging**
